#!/bin/sh
if [ "${SSH_ZONE-}" ]
then
    profile=$SSH_ZONE
    shell="zshell $SSH_ZONE"
else
    profile=Default
    shell="bash"
fi
#!/bin/sh
gnome-terminal --tab-with-profile=$profile \
               --title=btn/doc \
	       --command="bash -c 'cd ~/btn/doc;$shell'" \
               --tab-with-profile=$profile \
               --title=btn/data \
	       --command="bash -c 'cd ~/btn/data;$shell'"
