#!/bin/sh
if [ "${SSH_ZONE-}" ]
then
    profile=$SSH_ZONE
    shell="zshell $SSH_ZONE"
else
    profile=Default
    shell="bash"
fi
#!/bin/sh
gnome-terminal --tab-with-profile=$profile \
               --title=btn/include \
	       --command="bash -c 'cd ~/by-the-numbers/btn/include;$shell'" \
               --tab-with-profile=$profile \
               --title=btn/src \
	       --command="bash -c 'cd ~/by-the-numbers/btn/src;$shell'" \
               --tab-with-profile=$profile \
               --title=btn/test \
	       --command="bash -c 'cd ~/by-the-numbers/btn/test;$shell'" \
               --tab-with-profile=$profile \
               --title=btn/doc \
	       --command="bash -c 'cd ~/by-the-numbers/btn/doc;$shell'" \
               --tab-with-profile=$profile \
               --title=btn/data \
	       --command="bash -c 'cd ~/by-the-numbers/btn/data;$shell'"
