#! /bin/sh

cd ~/IMAGES
shopt -s nullglob
for dir1 in *OLYMP; do
    dir2=`echo $dir1 | tr A-Z a-z`
    echo $dir1
    for file1 in `ls $dir1`; do
	file2=`echo $file1 | tr A-Z a-z`
	if cmp -s $dir1/$file1 $dir2/$file2
	then
	    echo removing $dir1/$file1
	    rm -f $dir1/$file1
	elif test ! -r $dir2/$file2
	then
	    echo moving $dir1/$file1 to $dir2/$file2
	    mv $dir1/$file1 $dir2/$file2
	fi
    done
    echo removing $dir1
    rmdir $dir1

    ls -l
done
