#!/bin/sh
if [ "${SSH_ZONE-}" ]
then
    profile=$SSH_ZONE
    shell="zshell $SSH_ZONE"
else
    profile=Default
    shell="bash"
fi
gnome-terminal --tab-with-profile=$profile \
               --title=layered/include \
	       --command="bash -c 'cd ~/layered/include;$shell'" \
               --tab-with-profile=$profile \
               --title=layered/src \
	       --command="bash -c 'cd ~/layered/src;$shell'" \
               --tab-with-profile=$profile \
               --title=layered/test \
	       --command="bash -c 'cd ~/layered/test;$shell'" \
               --tab-with-profile=$profile \
               --title=layered/doc \
	       --command="bash -c 'cd ~/layered/doc;$shell'"
