#!/bin/sh
if [ "${SSH_ZONE-}" ]
then
    profile=$SSH_ZONE
    shell="zshell $SSH_ZONE"
else
    profile=Default
    shell="bash"
fi
gnome-terminal --tab-with-profile=$profile \
               --title=min/include \
	       --command="bash -c 'cd ~/min/include;$shell'" \
               --tab-with-profile=$profile \
               --title=min/src \
	       --command="bash -c 'cd ~/min/src;$shell'" \
               --tab-with-profile=$profile \
               --title=min/test \
	       --command="bash -c 'cd ~/min/test;$shell'" \
               --tab-with-profile=$profile \
               --title=min/doc \
	       --command="bash -c 'cd ~/min/doc;$shell'"
