#!/bin/csh -f
source ~/.lsbackuprc
echo rsync -av --delete $argv[2-]:q $argv[1]:q/ \
    ${LINKACCOUNT}@${LINKSTATION}:walton3/$argv[1]:q
rsync -av --delete $argv[2-]:q $argv[1]:q/ \
    ${LINKACCOUNT}@${LINKSTATION}:walton3/$argv[1]:q
